# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91fa40f3eeb2c8b632995502dbe52bf293fb3d7d1d4f43d7867b94bdadbbf7ffb3897ad88d7249cd3cbb8b8b72194d4db12c3f2ddc5534ce3e81f8d8125fd339

test:
  secret_key_base: 5f87c947099c7173e7109e55f938fb5125663a3ec36fc7b106b32e9920b9e1d51d73c280717ae581d7c420e2395a0b11c03db426f8db016a8647dc17043c3eec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
